<?php $this->pageTitle=Yii::app()->name . ' - Partial View'; ?>

<h1>Hello! I am a complete View!</h1>

<p>The contents of this page will always be fully rendered in normal circumstances, but
	partially rendered when answering to an AJAX request.</p>

<p>My path is ""<?php echo __FILE__; ?>" and my URL is "
	<?php
	$url = $this->createAbsoluteUrl('site/completeView'); 
	echo CHtml::link($url, $url); 
	?>"</p>

<p>Quisque tristique rhoncus fermentum. Mauris consectetur, justo sed lobortis pharetra, tortor lacus dignissim purus, vel suscipit diam magna non sapien. Aenean sed molestie neque. Cras ac mi turpis. Aenean ornare consectetur dui, vel varius nisi vulputate in. Donec mollis augue in nisi malesuada id egestas dolor elementum. Nullam eu dictum mauris. Mauris risus mauris, facilisis vitae pharetra sed, pellentesque tempus justo. Duis bibendum dignissim libero quis luctus. Sed a nisl est, quis facilisis purus.</p>

<p>Donec eget orci odio. Nulla ultricies diam eu nisl egestas elementum. Suspendisse eu purus at orci vulputate ultrices a facilisis est. Nunc volutpat sapien ac leo dictum feugiat. Duis purus augue, lobortis vitae porttitor mattis, pulvinar vitae augue. Vestibulum sed justo eros, et consectetur justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus quis enim est. Morbi imperdiet cursus commodo. Mauris commodo tempor nibh vel feugiat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis venenatis lobortis vestibulum. Proin dui tortor, eleifend in tincidunt eu, viverra eu enim.</p>

<p>Donec consectetur mattis congue. Sed commodo justo eu sem accumsan rutrum. Vivamus pulvinar blandit egestas. Phasellus diam arcu, vehicula id blandit ac, ornare ut leo. Duis vestibulum semper placerat. Sed ac odio lectus. Aliquam non risus vel velit mattis sollicitudin non id velit. Sed cursus varius urna quis tincidunt.</p>

<p>Duis sapien arcu, pulvinar sed auctor lobortis, viverra at diam. Nulla scelerisque lobortis semper. Proin tincidunt lacus at arcu tristique porta. In semper, nibh a consequat ultricies, augue dui gravida lectus, et pretium elit enim nec libero. Mauris varius sagittis magna in blandit. Suspendisse tellus elit, rutrum quis consequat id, ultricies vitae lorem. Nulla facilisi. Nunc feugiat sem vel dolor aliquet interdum. Maecenas consequat fringilla urna, quis euismod nunc dictum a. Integer at mi quis enim facilisis tempus. Suspendisse potenti. Etiam a felis ac lacus rhoncus mattis. Nunc faucibus placerat risus eget vestibulum. Donec venenatis, ante ac eleifend porta, leo erat tempus erat, quis consequat arcu augue nec velit. Praesent non dictum diam. Sed pellentesque libero nec elit hendrerit eu vehicula nibh euismod.</p>

<p>Donec tempus neque nec magna bibendum id gravida lectus consectetur. Aliquam erat volutpat. Vestibulum elit sem, ultrices at fermentum et, laoreet sed mauris. Aenean sit amet orci turpis, eu varius odio. Nam bibendum lobortis facilisis. Integer justo mauris, volutpat quis volutpat eu, accumsan eget nisi. Mauris porttitor tristique nulla, ut ullamcorper augue dictum iaculis. Sed viverra magna vitae orci blandit a tristique orci lobortis. Donec vel libero non mauris volutpat accumsan tincidunt vitae dolor. Phasellus sit amet urna ac lorem tincidunt rutrum. Pellentesque rhoncus, massa ac volutpat auctor, leo sem lobortis lorem, vitae venenatis lorem leo vel metus.</p>

<p>Morbi sagittis massa et lorem vehicula eget cursus metus fermentum. Nunc vehicula ligula adipiscing sem congue dignissim. Curabitur dignissim mollis mauris in imperdiet. Aliquam erat volutpat. Donec placerat laoreet iaculis. Nunc vitae ipsum vel nibh feugiat dignissim a ut lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus venenatis tempus augue, sed viverra ipsum semper sed. Maecenas faucibus hendrerit odio. Morbi adipiscing mauris in ligula rutrum quis ullamcorper tortor rutrum. Sed ut quam orci, ut condimentum erat. Maecenas porttitor risus vitae risus ultricies consectetur.</p>

<p>Morbi mi libero, sollicitudin id egestas ornare, auctor id augue. Vivamus ac lorem purus. In fermentum, lectus eu vulputate pellentesque, leo nunc ultricies urna, in egestas turpis mauris nec odio. Vestibulum consectetur pulvinar hendrerit. Phasellus nec eros eu erat euismod auctor ut dictum leo. Duis eu condimentum lacus. Aenean et felis tellus, nec ultrices velit.</p>

<p>Sed suscipit ligula vitae lacus fringilla eu cursus lacus gravida. Ut lacus nunc, mattis nec mollis sed, cursus sed tortor. In velit nulla, vulputate ac vehicula a, venenatis vitae diam. Nulla facilisi. Sed mauris diam, scelerisque ut rutrum vitae, pulvinar non orci. Proin nec purus risus. Ut nec est sit amet mauris lacinia gravida at vitae leo. Donec nulla lacus, elementum ut ornare quis, tincidunt vitae est. Etiam ut lacus nibh.</p>

<p>Pellentesque vitae purus elit. Sed vel dolor vel magna porttitor tempor id sed dui. Nam et mauris sem. Vestibulum ornare nunc est. Ut porta nulla vitae felis semper non condimentum magna fermentum. Aenean arcu orci, iaculis quis feugiat ac, ultrices ac lorem. Etiam consectetur velit id ligula porttitor sit amet convallis mauris tempor. Cras et turpis sed nibh tempor luctus id non ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce sed accumsan sapien. Quisque et posuere sem. Cras tortor mi, tristique in accumsan eget, pharetra in justo. Vestibulum sit amet fermentum sapien.</p>

<p>Nulla nunc justo, bibendum eu sodales eget, posuere nec odio. Aenean hendrerit, lorem vel adipiscing consectetur, leo mi eleifend sapien, et pellentesque velit ipsum in nibh. Maecenas porta, nulla sed pharetra dictum, nulla ante imperdiet metus, a luctus enim enim id tortor. Curabitur accumsan consectetur porttitor. Mauris dapibus blandit neque at lacinia. Nunc neque velit, adipiscing vel pretium eget, adipiscing sed sapien. Suspendisse molestie nisi et mauris iaculis sed feugiat enim dignissim. Nam porttitor, diam ac imperdiet feugiat, nisl ligula malesuada velit, vitae pulvinar tortor nisl non lectus. Fusce nunc nisi, tincidunt in sagittis ut, ultrices a neque. Nam porttitor egestas commodo. Suspendisse eget leo nec turpis lobortis imperdiet at vitae justo.</p>

<p>Vestibulum ligula eros, sagittis id iaculis sit amet, aliquam ut augue. Nullam in risus nec sapien suscipit auctor nec quis enim. Suspendisse faucibus auctor ligula, eget iaculis sapien feugiat eu. Nulla nec velit dapibus velit tincidunt aliquet. Praesent bibendum sodales suscipit. Aliquam commodo ante nec turpis tempus ac iaculis purus dignissim. Proin blandit tincidunt velit, nec faucibus nunc semper sed. Vestibulum elementum risus nec nibh varius sed molestie nulla pretium. Quisque interdum volutpat massa, non dapibus odio ultricies vitae. Integer accumsan aliquet mi, ac tincidunt libero porta sit amet. Vivamus elit orci, tincidunt rhoncus hendrerit quis, sollicitudin vel nibh. Mauris eget leo dictum arcu ullamcorper fermentum eget sed neque. Donec sagittis porta nisi vel viverra.</p>

<p>Fusce at scelerisque quam. Sed ut est turpis, nec ornare lorem. Suspendisse quis sapien quis justo tristique dignissim nec eget justo. Maecenas quis lectus eros, eget varius lorem. Nullam risus tellus, consectetur eu convallis sit amet, sollicitudin vitae dui. In dignissim fringilla massa, et pellentesque ligula consequat id. Vivamus condimentum commodo odio, in convallis risus pulvinar id. Etiam consequat sodales hendrerit. Aliquam lacinia, urna vulputate sollicitudin lacinia, risus erat elementum tortor, imperdiet cursus tortor mauris ut magna. Sed facilisis justo id erat tincidunt lobortis.</p>

<p>Sed cursus turpis ac orci hendrerit sed faucibus tellus volutpat. Nam auctor nibh et metus varius ut mollis lectus congue. Suspendisse mi libero, volutpat ac facilisis quis, imperdiet id nisl. Pellentesque sed molestie mi. Suspendisse faucibus lorem et est porttitor sodales. Sed cursus lacus vel ipsum rhoncus condimentum. Nullam volutpat, metus euismod tincidunt accumsan, risus diam rhoncus metus, sed venenatis est purus ultrices augue. In imperdiet dolor ullamcorper neque sodales pretium. Curabitur ipsum sapien, faucibus sit amet imperdiet ut, lobortis vel lorem. Aenean dapibus fermentum blandit. Suspendisse euismod pretium dapibus. Pellentesque tempus, mauris quis accumsan convallis, urna eros posuere mi, at pharetra diam nisl et tortor. In quis orci nec tellus gravida ullamcorper. Phasellus diam mi, malesuada eget faucibus ut, convallis eget nunc. Suspendisse a erat ut dolor bibendum dapibus vitae sed lorem.</p>

<p>Nulla facilisi. Sed aliquet dictum justo, accumsan mollis justo scelerisque sed. Nunc pharetra, purus at iaculis eleifend, ante augue pellentesque risus, nec lacinia turpis sem blandit mauris. Donec placerat turpis eu risus aliquam sed dapibus sapien ullamcorper. Maecenas ullamcorper justo in felis suscipit nec lobortis lacus vestibulum. Vestibulum augue velit, convallis rutrum tincidunt sit amet, accumsan ut odio. Vestibulum eleifend enim eget velit dapibus quis egestas est mollis. Praesent pulvinar dignissim tortor, sed faucibus dui egestas nec. Nulla erat est, commodo et molestie sit amet, dapibus ut nibh. Maecenas cursus lacus libero, sed porta libero. Quisque a diam enim, sed scelerisque nulla. Aenean tellus turpis, ornare non tincidunt at, lacinia et ante. Quisque tellus odio, vulputate cursus tempus id, elementum vel diam. Nunc id odio non neque eleifend mattis. Vestibulum tincidunt, nisl et blandit ullamcorper, diam velit blandit lectus, eget elementum nisl nulla non erat.</p>

<p>Sed in nisi ac quam facilisis sollicitudin. Aliquam erat volutpat. Duis at molestie metus. Phasellus ullamcorper malesuada nulla non laoreet. Pellentesque odio enim, consequat eu porta eu, ornare non dolor. Donec condimentum convallis nisl eget imperdiet. Mauris pharetra suscipit magna a vestibulum. Ut hendrerit semper imperdiet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti. Curabitur placerat placerat tortor eu pharetra. Phasellus dapibus mi ut urna interdum nec dapibus massa mollis. Vestibulum pellentesque convallis nisl venenatis auctor. Sed lorem leo, ultricies varius pulvinar vel, rhoncus eget augue. Pellentesque in nulla vitae lorem euismod gravida. Mauris at tellus eu mauris accumsan aliquam nec eu tortor.</p>

<p>Nunc facilisis diam a tellus aliquet in aliquam tellus fringilla. Vivamus malesuada pulvinar libero vitae commodo. In hac habitasse platea dictumst. Nam et nunc lectus, a scelerisque leo. Aenean sed ligula vel orci laoreet tincidunt. Sed ornare metus ut nisi interdum imperdiet. Aenean eu justo lectus. Maecenas in mauris libero. Aliquam erat volutpat. Sed nisl nibh, condimentum a facilisis id, bibendum ac felis.</p>

<p>Pellentesque blandit auctor sem, sed rutrum est commodo posuere. Cras vestibulum ullamcorper felis, eu sodales lorem gravida vel. Etiam nulla magna, euismod nec ultrices a, dapibus eu diam. Donec vitae sapien sit amet sapien tristique consequat. Nullam bibendum ante sed elit facilisis cursus. Proin magna velit, aliquam id sodales a, dapibus at odio. Donec neque ipsum, mattis eu facilisis et, sagittis non orci. Cras tristique pretium nibh, nec feugiat lacus porta nec. Ut posuere elementum velit vel dictum. Etiam condimentum sodales magna in pulvinar. Curabitur justo orci, iaculis in bibendum et, cursus ac magna. Donec lacinia risus ut dolor accumsan vitae mollis justo cursus. Nam fringilla, tortor quis dapibus hendrerit, nisl ligula tincidunt risus, nec lacinia ante velit luctus mauris. Quisque congue elit ut lacus malesuada at condimentum leo mollis.</p>

<p>Maecenas aliquet fringilla velit eget faucibus. Proin vitae purus at eros vehicula feugiat at vitae elit. Sed pellentesque sagittis iaculis. Phasellus ut condimentum lorem. Aenean sed odio et nulla feugiat consectetur et sed quam. In vitae mauris mi. Fusce iaculis pellentesque mauris a tincidunt. Nullam orci est, accumsan id vestibulum in, rhoncus quis magna. Praesent lectus leo, rhoncus a euismod ac, consequat eget diam. Nulla facilisi. Aliquam risus justo, condimentum ut adipiscing a, iaculis vel lacus. Cras rhoncus sem quis leo luctus ultricies. Vestibulum eget metus ac velit commodo viverra. Sed pharetra sem porttitor enim luctus non euismod ante porta.</p>

<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus lorem nisl, mattis vitae rutrum eget, egestas in dui. Fusce dapibus elementum dui, vitae ullamcorper augue tincidunt sit amet. Proin in ligula erat. Pellentesque auctor molestie justo id aliquet. Curabitur vehicula eros sed orci malesuada a convallis arcu iaculis. Mauris velit odio, bibendum ac porta in, auctor vitae eros. Nam est tellus, tincidunt non pellentesque ut, fermentum sed tortor.</p>

<p>Proin sapien enim, dapibus quis consectetur semper, pretium ultrices mauris. Quisque dictum mauris eu tellus tristique sollicitudin. Nam posuere cursus augue sit amet adipiscing. Nullam mollis imperdiet erat at sagittis. Ut eu lectus at quam gravida molestie. Morbi ultricies dui vitae nisl porttitor convallis. Etiam imperdiet iaculis ornare. Nulla dui nibh, vulputate a vulputate eu, fringilla eu ligula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur vel sapien elit, nec pellentesque nisi.</p> 